# Generated by Django 5.0.6 on 2024-06-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
